### ISSUE TITLE
invalid-api-key

### ISSUE THREAD

**Issue by GianlucaCerilli** [bourdakos1/Object-Detection#3]
Hi Nick,

very nice tutorial here https://medium.com/ibm-watson/dont-miss-your-target-object-detection-with-tensorflow-and-watson-488e24226ef3 ! 
But when I try to run the ¨python3 object_detection.py¨ I get the following error:

**Downloading model... (This may take over 5 minutes)
Model already downloaded
Loading model...
detecting...
Traceback (most recent call last):
  File "object_detection.py", line 108, in <module>
    results = visual_recognition.classify(images_file=images_file, parameters=parameters)
  File "/home/gianluca/venv/lib/python3.5/site-packages/watson_developer_cloud/visual_recognition_v3.py", line 119, in classify
    accept_json=True)
  File "/home/gianluca/venv/lib/python3.5/site-packages/watson_developer_cloud/watson_service.py", line 409, in request
    error_info)
watson_developer_cloud.watson_service.WatsonApiException: Error: invalid-api-key, Code: 403**

Do you have any idea about it? 
Thank you very much!

**Comment by bourdakos1** [comment]
ah sorry, this repo is a bit dated. They changed the name of the api variable name to something like iam_apikey. I can look at the docs and update the repo

**Comment by GianlucaCerilli** [comment]
Thank you very much for the immediate reply and for the availability.
I am following your really nice article "Custom Object Detection with Tensorflow". Is there something dated too in that article or is it possible to follow it? Do you also know if it's possible to use the final script (object tracking) in ROS kinetic?

Thank you very much again!

**Comment by GianlucaCerilli** [comment]
Hi @bourdakos1 ,
can you tell me something about my last message?

Thank you very much!

**Comment by bourdakos1** [comment]
Sorry I didn’t see this until now. I don’t know much about ROS kinetic so I’m not sure if this is compatible or not. Also the article should be fairly up to date. The only part that is out of date is the Watson api. The Watson api has been changing a lot recently and doesn’t play a large roll in the results, so you could probably remove it from the project.

**Comment by GianlucaCerilli** [comment]
Hi @bourdakos1 ,
I think I can try to train the network without Watson (I have a NVIDIA Qaudro p2000 and I have 800 images for one only custom object).

I am trying to run your code out of the box (I am using tensorflow-gpu with python 2.7) just to see if everything works before running my training, but If I directly run the ¨object_detection_runner.py¨ it says that I need the frozen_interference_graph. 
So, when I try to follow the steps under the ¨Usage¨ paragraph, I have errors.

E.g. when I run the script to train the model, I get:

> INFO:tensorflow:Scale of 0 disables regularizer.
> INFO:tensorflow:Scale of 0 disables regularizer.
> WARNING:tensorflow:From /home/gianluca/git/Custom-Object-Detection/object_detection/trainer.py:176: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please switch to tf.train.create_global_step
> WARNING:tensorflow:From /home/gianluca/venv/local/lib/python2.7/site-packages/tensorflow/python/training/input.py:187: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> To construct input pipelines, use the `tf.data` module.
> WARNING:tensorflow:From /home/gianluca/venv/local/lib/python2.7/site-packages/tensorflow/python/training/input.py:187: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> To construct input pipelines, use the `tf.data` module.
> WARNING:tensorflow:From /home/gianluca/git/Custom-Object-Detection/object_detection/core/preprocessor.py:1922: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
> Instructions for updating:
> Use the `axis` argument instead
> INFO:tensorflow:Scale of 0 disables regularizer.
> INFO:tensorflow:Scale of 0 disables regularizer.
> INFO:tensorflow:Scale of 0 disables regularizer.
> INFO:tensorflow:Scale of 0 disables regularizer.
> WARNING:tensorflow:From /home/gianluca/git/Custom-Object-Detection/object_detection/core/box_predictor.py:371: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
> Instructions for updating:
> keep_dims is deprecated, use keepdims instead
> WARNING:tensorflow:From /home/gianluca/git/Custom-Object-Detection/object_detection/core/losses.py:269: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> 
> Future major versions of TensorFlow will allow gradients to flow
> into the labels input on backprop by default.
> 
> See `tf.nn.softmax_cross_entropy_with_logits_v2`.
> 
> WARNING:tensorflow:From /home/gianluca/git/Custom-Object-Detection/object_detection/builders/optimizer_builder.py:105: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please switch to tf.train.get_or_create_global_step
> INFO:tensorflow:Summary name Learning Rate is illegal; using Learning_Rate instead.
> Traceback (most recent call last):
>   File "object_detection/train.py", line 198, in <module>
>     tf.app.run()
>   File "/home/gianluca/venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "object_detection/train.py", line 194, in main
>     worker_job_name, is_chief, FLAGS.train_dir)
>   File "/home/gianluca/git/Custom-Object-Detection/object_detection/trainer.py", line 218, in train
>     var_map, train_config.fine_tune_checkpoint))
>   File "/home/gianluca/git/Custom-Object-Detection/object_detection/utils/variables_helper.py", line 122, in get_variables_available_in_checkpoint
>     ckpt_reader = tf.train.NewCheckpointReader(checkpoint_path)
>   File "/home/gianluca/venv/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 314, in NewCheckpointReader
>     return CheckpointReader(compat.as_bytes(filepattern), status)
>   File "/home/gianluca/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt

Since this code is from last year, If you run it now everything works or do you have some errors too?

Thank you very much!

**Comment by GianlucaCerilli** [comment]
HI @bourdakos1,

I am running now the training (800 images with a NVIDIA Quadrop2000). I wanted to ask you two things if possible.
I have the images in the _images_ folder listed as ¨image1, image2....image10, 11....¨ but in the _trainval.txt_ in another order, like ¨image100, ..., image109, image10, image110, ....¨. 
Is there a problem for the join association for the training?
The second thing I was not sure about is that if there is a possibility to check if the gpu is running instead of the cpu (by the way, I have tensorflow-gpu installed) for the training.

Thank you very much again

**Comment by GianlucaCerilli** [comment]
HI @bourdakos1,

I am running now the training (800 images with a NVIDIA Quadrop2000).

After having changed the xmls , trainval and labelmap files, the only other things to change are the values inside faster_rcnn_resnet101.config ?
I am using this config as you, but with only one custom object to detect. So, I have only changed **num_classes ** from 2 to 1.
Are there other changes to do?

Thank you very much again
